version: '3.5'

services:
  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
  redis:
    user: "${UID}:${GID}"
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  mongo:
    user: "${UID}:${GID}"
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/projects/textat/.db:/data/db
  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - 1025:1025
        - 8025:8025
  browserless:
    user: "${UID}:${GID}"
    image: browserless/chrome
    restart: always
    ports:
      - 3023:3000
    volumes:
      - ./back/apps/whatsapp-service/.sessions:/usr/src/app/user-data-dir
      - ./back/apps/whatsapp-service/.screenshots:/usr/src/app/user-screenshots-dir
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: 'true'
      WORKSPACE_EXPIRE_DAYS: 1
      ENABLE_CORS: 'true'
      CHROME_REFRESH_TIME: 86400000
      DEFAULT_BLOCK_ADS: 'true'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      ENABLE_XVBF: 'true'
      CHROME_PATH: '/usr/bin/google-chrome'
      USE_CHROME_STABLE: 'true'
      NODE_ENV: 'production'
      MAX_CONCURRENT_SESSIONS: 1
      DEFAULT_USER_DATA_DIR: /usr/src/app/user-data-dir
volumes:
  redis:
    driver: local
  mongo:
    driver: local
  browserless:
    driver: local
